version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.1
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python text.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: echo "Practical successfully done"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - test
        filters:
          branches:
              only: main
            